global:
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['docker.for.mac.host.internal:9100']
- job_name: 'traefik'
  scheme: http
  metrics_path: '/metrics'
  static_configs:
    - targets: ['docker.for.mac.host.internal:8080']