tls:
  certificates:
    - certFile: /certificates/certificate.cer
      keyFile: /certificates/mykey.pem.pkcs8
  stores:
    default:
      defaultCertificate:
        certFile: /certificates/certificate.cer
        keyFile: /certificates/mykey.pem.pkcs8